### ISSUE TITLE
Bug d'affichage "lieux de distri"

### ISSUE THREAD

**Issue by t-h-w** [j-fish/cetcal#2]
@PaulBisserier 
Ci-dessous, 2 bugs.
N°1 : le libellé se repli sur mobil. Il doit être dans une colonne. Ce libellé doit s'étendre sur toute la largeur (en mobil ou écran moyen/large).
N°2 : on va placer le <select> type au-dessus du champ de recherche car en mobil, la page devient illisible. Utiliser deux class row (un pour chaque input group).
![image](https://user-images.githubusercontent.com/6128309/107326925-8ef0d880-6aac-11eb-9ab7-bd43b975563b.png)

**Comment by t-h-w** [comment]
capture d'écran:
![Sans titre](https://user-images.githubusercontent.com/6128309/107327092-cd869300-6aac-11eb-9cab-62bb9179e038.png)

**Comment by PaulBisserier** [comment]
fait

**Comment by t-h-w** [comment]
Imépc !
