### ISSUE TITLE
Bug affichage "lieux de dist"

### ISSUE THREAD

**Issue by t-h-w** [j-fish/cetcal#3]
@PaulBisserier La class bootstrap "card" ne se comporte pas correctement et le margin n'est présent que tous les 3 occurences. Il faut créer un class cet-card pour forcer un margin-bottom identique à chaque card en mode mobil (écran larges ou moyens RAS). capture ci-dessous : 
![image](https://user-images.githubusercontent.com/6128309/107327357-4ede2580-6aad-11eb-88e8-4b6052f16ad3.png)

**Comment by PaulBisserier** [comment]
fait

**Comment by t-h-w** [comment]
J'ai testé dans les deux contextes : mobil et large > RAS. Merci !
