### ISSUE TITLE
Parse error: syntax error, unexpected end of file in ...fichedetailleeprd.php

### ISSUE THREAD

**Issue by t-h-w** [j-fish/cetcal#4]
@PaulBisserier 
Ce bug de parsing survient car quand tu ouvre une ligne php comme ceci : 
`<?php foreach ($produits as $produit): ?>`
, il faut la clôturer de la même manière et avec la même syntaxe (`<?php ... ?>` et non pas `<? ... ?>`). Actuellement,` ce n'est pas le cas : 
`<?endforeach;?>`

**La version php de prod réagit également avec une parse exception.**

**Comment by PaulBisserier** [comment]
fait

**Comment by t-h-w** [comment]
Yes : D
